services:
  - type: web
    name: clinic-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn clinic_backend.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: DJANGO_SETTINGS_MODULE
        value: clinic_backend.settings
      - key: SECRET_KEY
        value: replace-this-with-a-secure-secret
      - key: DEBUG
        value: "True"
